name: Test Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'foo/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "hello world"
